name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # Create a zip file with the required files
          zip -r ${{ github.event.repository.name }}.zip dist
          
          # Copy the required files from dist directory for individual upload
          cp dist/main.js .
          cp dist/manifest.json .
          
          # Create GitHub release with all required assets
          gh release create "$tag" \
            --title "$tag" \
            --notes "Release $tag of the plugin." \
            ${{ github.event.repository.name }}.zip main.js manifest.json 